#ifndef CONFIG_H
#define CONFIG_H

#define BUFFERS_COUNT 4
#define IMAGE_WIDTH 320
#define IMAGE_COLUMNS IMAGE_WIDTH
#define IMAGE_HEIGHT 240
#define IMAGE_ROWS IMAGE_HEIGHT
#define IMAGE_SIZE IMAGE_WIDTH*IMAGE_HEIGHT*3

#define GRID_ROWS 9
#define GRID_COLUMNS 9

#endif
