#!/bin/bash

UART=$(cat /sys/devices/bone_capemgr.8/slots|grep UART1)
if [ "x$UART" == "x" ]; then
	echo "LOAD UART1"
fi
avrdude -v -v -v -v -patmega328p -carduino -P/dev/ttyO1 -b57600 -D -Uflash:w:/tmp/arduino.hex:i
